name: Gitleaks
on: push
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract Depth
        id: pr_depth
        shell: bash
        run: echo "##[set-output name=count;]$(git rev-list origin/master.. --count)"
      - name: Gitleaks Action
        continue-on-error: true
        uses: docker://zricethezav/gitleaks:v7.3.0
        with:
          args: gitleaks --depth=${{ steps.pr_depth.outputs.count }} --path . --redact -v --format=sarif --report=gitleaks.sarif
      - uses: github/codeql-action/upload-sarif@v1
        continue-on-error: true
        with:
          sarif_file: gitleaks.sarif
